# .github/workflows/ci.yaml
# This workflow runs comprehensive CI checks on every push and pull request to the main branch.
# It includes type checking, linting, testing, and building to ensure code quality and integrity.

name: Continuous Integration

on:
  push:
    branches:
      - main
      - "feature/**"
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [main]

jobs:
  ci:
    name: Run CI Checks
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        with:
          version: 10

      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          # Use the latest Long-Term Support version of Node.js
          node-version: "lts/*"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run comprehensive CI checks
        run: pnpm run ci
