# .github/workflows/release.yaml
# This workflow is manually triggered to create a new GitHub Release.
# It uses semantic-release to automatically determine the version number,
# generate a changelog, and create the release tag.

name: Create GitHub Release

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    # These permissions are required for semantic-release to create releases,
    # push tags, and comment on issues/PRs.
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance

    steps:
      - name: Checkout repository
        uses: actions/checkout@09d2acae674a48949e3602304ab46fd20ae0c42f
        with:
          # Fetch all history for all branches and tags, which is required by semantic-release
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@08f58d1471bff7f3a07d167b4ad7df25d5fcfcb6
        with:
          # Use the latest Long-Term Support version of Node.js
          node-version: "lts/*"
          cache: "npm"

      - name: Install dependencies
        # Using 'npm ci' is a best practice for CI environments as it's faster and more secure
        run: npm ci

      - name: Run comprehensive CI checks
        run: npm run ci

      - name: Create Release
        # Use the semantic-release script defined in package.json
        # This will analyze commits, determine version, generate changelog, and create GitHub release
        run: npm run semantic-release
        env:
          # GitHub token is automatically provided by GitHub Actions
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
