# .github/workflows/version.yml
name: Version Packages

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  version:
    # Skip if it's the bot's own version commit (prevents infinite loop)
    if: github.event.head_commit.message != 'Version packages [skip ci]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        with:
          version: 10

      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 #v4
        with:
          # Use the latest Long-Term Support version of Node.js
          node-version: "lts/*"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run comprehensive CI checks
        run: pnpm run ci

      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@e0145edc7d9d8679003495b11f87bd8ef63c0cba # v1.5.3
        with:
          # Only version, don't publish
          version: npm run version
          commit: "Version packages"
          title: "Version packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
